// Canonical owner-facing property editor schema.
//
// Both Build from Scratch and Advanced Editor import this file. Keep field keys
// aligned with the Airtable/Supabase bridge and the public property master page;
// never fork category definitions inside individual editor components.
export const CATEGORIES = [
  { id: "residential", icon: "🏠", label: "Residential" },
  { id: "commercial", icon: "🏢", label: "Commercial" },
  { id: "str", icon: "🌙", label: "Short-Term Rental" },
  { id: "hospitality", icon: "🏨", label: "Hospitality" },
  { id: "restaurants", icon: "🍽️", label: "Restaurant" },
  { id: "venues", icon: "🎤", label: "Venue" },
];

export const CATEGORY_FIELDS = {
  residential: [
    { key: "Beds", label: "Bedrooms", type: "number", proOnly: false },
    { key: "Baths", label: "Bathrooms", type: "number", proOnly: false },
    { key: "Floor_Area_Sqm", label: "Floor area (sqm)", type: "number", proOnly: false },
    { key: "Lot_Area_Sqm", label: "Lot area (sqm)", type: "number", proOnly: false },
    { key: "Parking_Slots", label: "Parking slots", type: "number", proOnly: false },
    { key: "Furnishing", label: "Furnishing", type: "select", options: ["Bare", "Semi-Furnished", "Fully Furnished"], proOnly: false },
    { key: "RS_Floor_Level", label: "Floor Level", type: "text", proOnly: false },
    { key: "RS_View", label: "View", type: "text", proOnly: false },
    { key: "RS_Turnover_Date", label: "Turnover Date", type: "text", proOnly: false },
    { key: "RS_Pet_Policy", label: "Pet Policy", type: "text", proOnly: false },
    { key: "RS_Assoc_Dues", label: "Assoc Dues (₱/mo)", type: "number", proOnly: false },
    { key: "RS_Studio_Flag", label: "Studio Unit", type: "checkbox", proOnly: false },
    { key: "Amenities", label: "Amenities", type: "text", proOnly: false },
    { key: "TitleStatus", label: "Title Status", type: "text", proOnly: false },
    { key: "RS_Price", label: "Residential Price", type: "number", proOnly: false },
    { key: "RS_Price_Per_Sqm", label: "Price / sqm", type: "number", proOnly: true },
    { key: "RS_Payment_Terms", label: "Payment Terms", type: "text", proOnly: true },
  ],
  commercial: [
    { key: "CM_Rent_Per_Sqm", label: "Published rent (₱/sqm/mo)", type: "number", proOnly: false },
    { key: "CM_Total_GLA", label: "Total GLA (sqm)", type: "number", proOnly: false },
    { key: "CM_Floor_Plate_Sqm", label: "Floor Plate (sqm)", type: "number", proOnly: false },
    { key: "CM_Building_Grade", label: "Building grade", type: "select", options: ["Premium", "Grade A", "Grade B", "Grade C"], proOnly: false },
    { key: "CM_Hand_Over_Condition", label: "Hand-over condition", type: "select", options: ["Bare Shell", "Warm Shell", "Fitted", "As-is-where-is"], proOnly: false },
    { key: "CM_Availability_Status", label: "Availability", type: "text", proOnly: false },
    { key: "CM_Min_Lease_Term", label: "Min. Lease Term", type: "text", proOnly: false },
    { key: "CM_Certification", label: "Certification", type: "text", proOnly: false },
    { key: "PEZA", label: "PEZA Accredited", type: "checkbox", proOnly: false },
    { key: "CM_CAMC_Per_Sqm", label: "CAMC (₱/sqm/mo)", type: "number", proOnly: false },
    { key: "CM_AC_Charges", label: "A/C charges", type: "number", proOnly: false },
    { key: "CM_AC_System", label: "AC System", type: "text", proOnly: true },
    { key: "CM_Reserved_Parking", label: "Reserved Parking", type: "text", proOnly: true },
    { key: "CM_Escalation_Rate", label: "Escalation Rate", type: "text", proOnly: true },
    { key: "CM_Fit_Out_Allowance", label: "Fit-out Allowance", type: "text", proOnly: true },
    { key: "CM_Rent_Free_Period", label: "Rent-free Period", type: "text", proOnly: true },
    { key: "CM_Parking_Ratio", label: "Parking Ratio", type: "text", proOnly: true },
    { key: "CM_Backup_Power", label: "Backup Power", type: "text", proOnly: true },
    { key: "CM_Floor_Loading", label: "Floor Loading", type: "text", proOnly: true },
    { key: "CM_Internet_Providers", label: "Internet Providers", type: "text", proOnly: true },
    { key: "CM_Available_Units_Summary", label: "Available Units", type: "text", proOnly: true },
    { key: "CM_Towers_Zones", label: "Towers / Zones", type: "text", proOnly: true },
    { key: "CM_Cap_Rate", label: "Cap Rate (%)", type: "number", proOnly: true },
    { key: "CM_NOI", label: "NOI", type: "number", proOnly: true },
  ],
  str: [
    { key: "STR_Nightly_Rate", label: "Nightly rate (₱)", type: "number", proOnly: false },
    { key: "STR_Cleaning_Fee", label: "Cleaning Fee (₱)", type: "number", proOnly: false },
    { key: "STR_Max_Guests", label: "Max guests", type: "number", proOnly: false },
    { key: "STR_Avg_Rating", label: "Avg. Rating", type: "number", proOnly: false },
    { key: "STR_Bedrooms", label: "Bedrooms", type: "number", proOnly: false },
    { key: "STR_Bathrooms", label: "Bathrooms", type: "number", proOnly: false },
    { key: "STR_Min_Stay_Nights", label: "Minimum stay (nights)", type: "number", proOnly: false },
    { key: "STR_Check_In_Out", label: "Check-in / out", type: "text", proOnly: false },
    { key: "Amenities", label: "Amenities", type: "text", proOnly: false },
    { key: "STR_Weekend_Rate", label: "Weekend Rate (₱)", type: "number", proOnly: true },
    { key: "STR_Bed_Config", label: "Bed configuration", type: "text", proOnly: true },
    { key: "STR_Self_Check_In", label: "Self check-in available", type: "checkbox", proOnly: true },
    { key: "STR_House_Rules", label: "House Rules", type: "text", proOnly: true },
    { key: "STR_Cancellation_Policy", label: "Cancellation Policy", type: "text", proOnly: true },
    { key: "STR_Permit_Accreditation", label: "DOT / LGU permit", type: "text", proOnly: true },
    { key: "STR_WiFi_Speed", label: "WiFi Speed", type: "text", proOnly: true },
  ],
  hospitality: [
    { key: "HOSP_Room_Count", label: "Room Count", type: "number", proOnly: false },
    { key: "HOSP_Star_Rating", label: "Star Rating", type: "number", proOnly: false },
    { key: "HOSP_FB_Outlets", label: "F&B Outlets", type: "number", proOnly: false },
    { key: "HOSP_Function_Rooms", label: "Function Rooms", type: "number", proOnly: false },
    { key: "HOSP_Operator_Brand", label: "Operator / Brand", type: "text", proOnly: false },
    { key: "HOSP_Room_Types", label: "Room Types", type: "text", proOnly: false },
    { key: "HOSP_Year_Built_Renovated", label: "Built / Renovated", type: "text", proOnly: false },
    { key: "Listed_Price", label: "Listed Price", type: "number", proOnly: false },
    { key: "HOSP_ADR", label: "ADR (₱)", type: "number", proOnly: true },
    { key: "HOSP_Occupancy_Rate", label: "Occupancy Rate (%)", type: "number", proOnly: true },
    { key: "HOSP_RevPAR", label: "RevPAR (₱)", type: "number", proOnly: true },
    { key: "HOSP_Cap_Rate", label: "Cap Rate (%)", type: "number", proOnly: true },
    { key: "HOSP_GFA", label: "GFA (sqm)", type: "number", proOnly: true },
    { key: "HOSP_Land_Area", label: "Land Area (sqm)", type: "number", proOnly: true },
  ],
  restaurants: [
    { key: "RST_Floor_Area_Sqm", label: "Floor Area (sqm)", type: "number", proOnly: false },
    { key: "RST_Seating_Capacity", label: "Seating capacity", type: "number", proOnly: false },
    { key: "RST_Kitchen_Condition", label: "Kitchen condition", type: "select", options: ["With Kitchen", "Bare", "Needs Build-out"], proOnly: false },
    { key: "RST_Foot_Traffic", label: "Foot traffic", type: "select", options: ["Low", "Medium", "High"], proOnly: false },
    { key: "RST_Frontage", label: "Storefront frontage", type: "text", proOnly: false },
    { key: "RST_Indoor_Outdoor", label: "Indoor / Outdoor", type: "text", proOnly: false },
    { key: "RST_Previous_Use", label: "Previous Use", type: "text", proOnly: false },
    { key: "RST_Rent", label: "Rent (₱/mo)", type: "number", proOnly: false },
    { key: "RST_Dues_CUSA", label: "Dues / CUSA (₱/mo)", type: "number", proOnly: false },
    { key: "RST_Hood_Exhaust", label: "Hood / exhaust present", type: "checkbox", proOnly: true },
    { key: "RST_Grease_Trap", label: "Grease trap present", type: "checkbox", proOnly: true },
    { key: "RST_Gas_Line", label: "Gas line available", type: "checkbox", proOnly: true },
    { key: "RST_Power_Capacity", label: "Power Capacity", type: "number", proOnly: true },
    { key: "RST_Delivery_Access", label: "Delivery Access", type: "text", proOnly: true },
    { key: "RST_Liquor_License", label: "Liquor license eligible", type: "text", proOnly: true },
    { key: "RST_FB_Zoning_Permit", label: "F&B Zoning Permit", type: "text", proOnly: true },
    { key: "RST_Ceiling_Height", label: "Ceiling Height", type: "text", proOnly: true },
    { key: "RST_Turnover_Condition", label: "Turnover Condition", type: "text", proOnly: true },
    { key: "RST_Parking", label: "Parking", type: "text", proOnly: true },
  ],
  venues: [
    { key: "VEN_Capacity_Seated", label: "Seated capacity", type: "number", proOnly: false },
    { key: "VEN_Capacity_Standing", label: "Standing capacity", type: "number", proOnly: false },
    { key: "VEN_Floor_Area_Sqm", label: "Floor Area (sqm)", type: "number", proOnly: false },
    { key: "VEN_Min_Booking_Hours", label: "Min Booking (hrs)", type: "number", proOnly: false },
    { key: "VEN_Indoor_Outdoor", label: "Indoor / Outdoor", type: "text", proOnly: false },
    { key: "VEN_Air_Conditioning", label: "Air-conditioned", type: "text", proOnly: false },
    { key: "VEN_Catering_Policy", label: "Catering policy", type: "select", options: ["In-house only", "External allowed", "Both"], proOnly: false },
    { key: "VEN_Rental_Rate", label: "Rental Rate (₱)", type: "number", proOnly: false },
    { key: "VEN_Rate_Basis", label: "Rate Basis", type: "text", proOnly: false },
    { key: "VEN_Layout_Configs", label: "Layout configurations", type: "text", proOnly: true },
    { key: "VEN_Ceiling_Height", label: "Ceiling Height", type: "text", proOnly: true },
    { key: "VEN_AV_Equipment", label: "AV equipment included", type: "text", proOnly: true },
    { key: "VEN_Power_Capacity", label: "Power Capacity", type: "text", proOnly: true },
    { key: "VEN_Parking", label: "Parking", type: "text", proOnly: true },
    { key: "VEN_Accessibility", label: "Accessibility", type: "text", proOnly: true },
    { key: "VEN_Noise_Curfew", label: "Noise curfew", type: "text", proOnly: true },
  ],
};
