import { supabase } from "./supabaseClient";

// 10MB for documents/images, 50MB for videos
const MAX_SIZES = {
  'image/jpeg': 10 * 1024 * 1024,
  'image/png': 10 * 1024 * 1024,
  'application/pdf': 10 * 1024 * 1024,
  'video/mp4': 50 * 1024 * 1024,
};

export const uploadAttachment = async (dealId, file) => {
  // 1. Client-side MIME Type Validation (Defense in Depth)
  if (!MAX_SIZES[file.type]) {
    throw new Error("Invalid file type. Only JPG, PNG, PDF, and MP4 are allowed.");
  }

  // 2. Client-side Size Validation
  const maxSize = MAX_SIZES[file.type];
  if (file.size > maxSize) {
    throw new Error(`File is too large. Maximum size is ${maxSize / (1024 * 1024)}MB for this file type.`);
  }

  // 3. Generate a secure, unique filename to prevent collisions and directory traversal
  const fileExt = file.name.split('.').pop().toLowerCase();
  const safeName = file.name.replace(/[^a-zA-Z0-9.\-]/g, '_');
  const uniqueFilename = `${Date.now()}-${Math.random().toString(36).substring(2, 9)}_${safeName}`;
  const filePath = `${dealId}/${uniqueFilename}`;

  // 4. Upload to Supabase Storage
  const { data, error } = await supabase.storage
    .from('chat_attachments')
    .upload(filePath, file, {
      cacheControl: '3600',
      upsert: false
    });

  if (error) {
    throw new Error(error.message || "Failed to upload file to secure storage.");
  }

  // 5. Generate Signed URL for immediate rendering
  // (Assuming RLS prevents direct public access, but signed URLs can be generated by users with SELECT access)
  const { data: urlData, error: urlError } = await supabase.storage
    .from('chat_attachments')
    .createSignedUrl(filePath, 60 * 60 * 24 * 7); // 7 days

  if (urlError) {
    throw new Error("Failed to generate access URL for attachment.");
  }

  return {
    path: filePath,
    url: urlData.signedUrl,
    name: file.name,
    type: file.type,
    size: file.size
  };
};
