/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "surface-tint": "#e3c285",
        "on-primary-container": "#533d0c",
        "on-tertiary": "#222f51",
        "surface-variant": "#353535",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "surface-container-low": "#1c1b1b",
        "on-secondary": "#313030",
        "secondary": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-highest": "#353535",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#394669",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#261900",
        "background": "#0e0e0e",
        "text-secondary": "#a0a0a0",
        "tertiary-container": "#9facd5",
        "surface-container": "#20201f",
        "primary": "#e5c487",
        "on-tertiary-container": "#334063",
        "tertiary-fixed": "#dae2ff",
        "gold-accent": "#c8a96e",
        "inverse-primary": "#735b28",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed": "#0b1a3b",
        "primary-fixed-dim": "#e3c285",
        "success": "#4caf50",
        "outline-variant": "#4d463a",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#c9c6c5",
        "on-primary-fixed-variant": "#594312",
        "surface": "#161616",
        "error-container": "#93000a",
        "surface-alt": "#222222",
        "tertiary-fixed-dim": "#b8c5f0",
        "error": "#f44336",
        "on-primary": "#402d00",
        "outline": "#998f81",
        "on-surface-variant": "#d0c5b5",
        "tertiary": "#bac7f2",
        "secondary-fixed": "#e5e2e1",
        "gold-muted": "#8a754d",
        "primary-fixed": "#ffdea3",
        "surface-dim": "#131313",
        "on-secondary-container": "#bab8b7",
        "text-primary": "#ffffff",
        "primary-container": "#c8a96e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "md": "16px",
        "xxl": "64px",
        "margin-desktop": "40px",
        "base": "4px",
        "sm": "8px",
        "margin-mobile": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "working-title": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-editorial": ["Georgia", "serif"],
        "display-md": ["Georgia", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Georgia", "serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "working-title": ["20px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-editorial": ["24px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-md": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "data-tabular": ["14px", { "lineHeight": "1", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
