/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "surface-tint": "#F7C64E",
        "on-primary-container": "#533d0c",
        "on-tertiary": "#222f51",
        "surface-variant": "rgb(var(--m3-surface-variant-ch) / <alpha-value>)",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "surface-container-low": "rgb(var(--m3-surface-container-low-ch) / <alpha-value>)",
        "on-secondary": "#313030",
        "secondary": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-highest": "#353535",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#394669",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#261900",
        "background": "rgb(var(--bg-ch) / <alpha-value>)",
        "text-secondary": "rgb(var(--text-secondary-ch) / <alpha-value>)",
        "tertiary-container": "#9facd5",
        "surface-container": "rgb(var(--m3-surface-container-ch) / <alpha-value>)",
        "primary": "#E8AE3C",
        "on-tertiary-container": "#334063",
        "tertiary-fixed": "#dae2ff",
        "gold-accent": "rgb(var(--accent-ch) / <alpha-value>)",
        "intel-cyan": "rgb(var(--intel-cyan-ch) / <alpha-value>)",
        "intel-magenta": "rgb(var(--intel-magenta-ch) / <alpha-value>)",
        "gold-bright": "rgb(var(--accent-bright-ch) / <alpha-value>)",
        "inverse-primary": "#6E531A",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed": "#0b1a3b",
        "primary-fixed-dim": "#F7C64E",
        "success": "#4caf50",
        "outline-variant": "#4d463a",
        "on-surface": "rgb(var(--m3-on-surface-ch) / <alpha-value>)",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#c9c6c5",
        "on-primary-fixed-variant": "#594312",
        "surface": "rgb(var(--surface-ch) / <alpha-value>)",
        "error-container": "#93000a",
        "surface-alt": "rgb(var(--surface3-ch) / <alpha-value>)",
        "tertiary-fixed-dim": "#b8c5f0",
        "error": "#f44336",
        "on-primary": "#402d00",
        "outline": "#998f81",
        "on-surface-variant": "#d0c5b5",
        "tertiary": "#bac7f2",
        "secondary-fixed": "#e5e2e1",
        "gold-muted": "var(--accent-muted)",
        "primary-fixed": "#ffdea3",
        "surface-dim": "#131313",
        "on-secondary-container": "#bab8b7",
        "text-primary": "rgb(var(--text-primary-ch) / <alpha-value>)",
        "primary-container": "#E8AE3C",
        "border": "var(--border)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "md": "16px",
        "xxl": "64px",
        "margin-desktop": "40px",
        "base": "4px",
        "sm": "8px",
        "margin-mobile": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["var(--font-geist-sans)", "Inter", "sans-serif"],
        "working-title": ["var(--font-geist-sans)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        "headline-editorial": ["var(--font-instrument-serif)", "Georgia", "serif"],
        "display-md": ["var(--font-instrument-serif)", "Georgia", "serif"],
        "body-md": ["var(--font-geist-sans)", "Inter", "sans-serif"],
        "data-tabular": ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        "body-sm": ["var(--font-geist-sans)", "Inter", "sans-serif"],
        "display-lg": ["Georgia", "serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "working-title": ["20px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-editorial": ["24px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-md": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "data-tabular": ["14px", { "lineHeight": "1", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
