export const CORE_ROLES = {
  seeker: {
    number: "01",
    short: "Seeker",
    label: "Buyer or tenant",
    thesis: "Move from browsing to a defensible shortlist.",
    summary: "Read public spaces, keep a private Board, compare context, and choose when a conversation is worth opening.",
    orbit: ["Discover", "Read", "Save", "Compare", "Inquire"],
    steps: [
      ["Discover", "Use the public directory, editorial surfaces, and location context to narrow the field."],
      ["Read", "Inspect the category-specific briefing, source labels, media, and known limitations."],
      ["Shortlist", "Save candidates privately on your device; sign in only when account continuity is useful."],
      ["Connect", "When ready, open an authenticated inquiry that follows the property’s current routing rules."],
    ],
    responsibility: "ScoutIt improves the information path; you remain responsible for independent legal, financial, physical, and technical due diligence.",
    primary: ["Explore properties", "/property"],
    secondary: ["Open your Board", "/wishlist"],
  },
  owner: {
    number: "02",
    short: "Owner",
    label: "Owner or developer",
    thesis: "Turn source material into a durable public record.",
    summary: "Build the private draft, attest to owner-authored facts, publish through the controlled bridge, and manage lifecycle continuity.",
    orbit: ["Source", "Structure", "Attest", "Publish", "Maintain"],
    steps: [
      ["Create", "Choose the guided workspace, advanced editor, CSV portfolio, or a PDF-assisted starting point."],
      ["Review", "Keep unsupported fields blank. PDF-assisted drafts require comparison with the supplied document."],
      ["Publish", "Owner-approved fields sync from Supabase to Airtable; the first public slug becomes canonical."],
      ["Maintain", "Edit, withdraw, or reactivate while preserving the URL, audit history, and required internal records."],
    ],
    responsibility: "Owner attestation confirms owner-authored facts; it is not a blanket independent verification of the property.",
    primary: ["Open owner onboarding", "/onboarding"],
    secondary: ["Review the publish model", "/layer/mantle#architecture"],
  },
  broker: {
    number: "03",
    short: "Broker",
    label: "Licensed broker",
    thesis: "Make representation visible and accountable.",
    summary: "Establish identity, submit a PRC claim, accept owner-authorized representation, and manage routed opportunities privately.",
    orbit: ["Identity", "Credential", "Authority", "Route", "Serve"],
    steps: [
      ["Identify", "Create the private account and public professional identity used across representation workflows."],
      ["Verify scope", "Submit the PRC credential claim. A credential label applies only to that credential and check."],
      ["Represent", "Representation becomes active through the owner–broker authority workflow, not a browser-local role flag."],
      ["Respond", "Manage routed inquiries, conversations, scheduling, and permitted account activity inside the dashboard."],
    ],
    responsibility: "Representation and credential checks do not guarantee a listing claim, transaction outcome, or continuing license status beyond the recorded scope.",
    primary: ["Meet the broker network", "/brokers"],
    secondary: ["Create an account", "/onboarding"],
  },
  professional: {
    number: "04",
    short: "Professional",
    label: "Spatial professional",
    thesis: "Attach skilled work to better space decisions.",
    summary: "Present a specialty, show relevant work, and participate in the service ecosystem around properties and spatial intelligence.",
    orbit: ["Specialty", "Profile", "Evidence", "Discovery", "Inquiry"],
    steps: [
      ["Specialize", "Choose the professional path that accurately reflects your work: photography, research, or event planning."],
      ["Present", "Build a public profile around real identity, specialty, and attributable work rather than generic claims."],
      ["Be discovered", "Appear in the relevant public network surface as records become available and approved."],
      ["Engage", "Move qualified interest into authenticated, permissioned account workflows."],
    ],
    responsibility: "Professional visibility depends on supported records and scoped checks; ScoutIt does not promise ranking, volume, or commercial outcome.",
    primary: ["Explore the network", "/layer/crust"],
    secondary: ["Create an account", "/onboarding"],
  },
};

export const CORE_ROLE_ORDER = Object.keys(CORE_ROLES);
