export const CRUST_SERVICE_KEYS = ["advisors", "photography", "research", "events"];

export const CRUST_SERVICE_DATA = Object.freeze({
  advisors: {
    navLabel: "Verified Advisors",
    eyebrow: "Representation & transaction guidance",
    status: "Live directory",
    statusTone: "live",
    title: "Licensed real estate advisors",
    summary: "Brokers and advisors help shortlist spaces, arrange viewings, explain representation, and guide negotiations within the authority of their professional role.",
    purpose: "Use an advisor when a property has moved from discovery into serious evaluation and you need a named professional responsible for the next conversation.",
    evidence: "A PRC Verified badge appears only after staff records supporting registry evidence. Profiles without that badge have not passed that specific check.",
    engage: "Engage before a viewing, offer, lease discussion, or representation decision. Independently confirm the person’s current license, authority, fees, and transaction terms.",
    boundary: "ScoutIt displays the roster and routes the connection. It is not the broker, representative, guarantor, appraiser, or party to the transaction.",
    rosterNote: "The live Airtable roster may be empty while the founding advisor cohort is reviewed. Empty means no qualifying public profile—not a hidden fallback.",
    cta: "Review advisor roster",
    href: "/brokers",
  },
  photography: {
    navLabel: "Space Photography",
    eyebrow: "Architectural documentation",
    status: "Profiles open · tools waitlisted",
    statusTone: "forming",
    title: "Space photographers",
    summary: "Architectural and interior photographers document the proportions, light, materials, and operational character of a space for listings, archives, and campaigns.",
    purpose: "Use a photographer when accurate visual documentation matters more than generic marketing imagery—before publication, repositioning, or a major editorial refresh.",
    evidence: "Provider profiles come from Supabase and can carry explicit Example, Pilot, and availability signals. ScoutIt does not imply portfolio ownership, insurance, credentials, or quality without evidence.",
    engage: "Engage after the space is presentation-ready and before publishing media. Confirm scope, usage rights, access, shot list, delivery format, and fees directly.",
    boundary: "The public roster is a profile and pre-registration surface. Commissioning and provider transaction tools remain unavailable until that workflow is operational.",
    rosterNote: "Example accounts are labelled at the destination. If no real public profiles qualify, the directory shows an honest founding-cohort empty state.",
    cta: "Browse photographer profiles",
    href: "/photographers",
    secondaryCta: "Create a provider profile",
    secondaryHref: "/onboarding",
  },
  research: {
    navLabel: "Site Research",
    eyebrow: "Ground truth & due diligence",
    status: "Profiles open · tools waitlisted",
    statusTone: "forming",
    title: "Site researchers",
    summary: "Researchers gather source-linked location, access, market, neighborhood, and field observations so a space decision can be tested against evidence beyond the listing.",
    purpose: "Use a researcher when a shortlist depends on local conditions, field verification, comparable context, or a question that public listing data cannot answer.",
    evidence: "Profiles may show Example, Pilot, and availability signals. Research findings require their own sources and review; a profile never makes every future claim verified by default.",
    engage: "Engage before due diligence closes or when a material unknown remains. Agree on the question, geography, source standard, field method, deadline, and evidence format.",
    boundary: "ScoutIt does not turn research into legal, engineering, valuation, or investment advice. Commission and bounty tools remain limited until the real workflow opens.",
    rosterNote: "Example accounts are labelled at the destination. An empty roster stays empty while the founding researcher cohort is assembled.",
    cta: "Browse researcher profiles",
    href: "/researchers",
    secondaryCta: "Create a provider profile",
    secondaryHref: "/onboarding",
  },
  events: {
    navLabel: "Event Design",
    eyebrow: "Venue transformation & production",
    status: "Profiles open · tools waitlisted",
    statusTone: "forming",
    title: "Event planners & space designers",
    summary: "Event planners coordinate the operational brief; event designers shape how a venue looks and feels. The specialties can overlap, but ScoutIt treats them as distinct professional capabilities.",
    purpose: "Use them after a venue is shortlisted and the guest journey, layout, production load, or creative transformation needs a specialist plan.",
    evidence: "Profiles may show Example, Pilot, and availability signals. ScoutIt does not guarantee credentials, supplier capacity, venue approval, safety compliance, or delivery quality.",
    engage: "Engage before contracting a venue or production team. Confirm role, scope, supplier authority, permits, insurance, capacity, safety responsibilities, schedule, and fees.",
    boundary: "The roster does not make ScoutIt the planner, designer, employer, venue operator, credentialing body, or guarantor. Matching and transaction tools are not yet open.",
    rosterNote: "Example accounts are labelled at the destination. No qualifying profiles produces a truthful founding-cohort empty state.",
    cta: "Browse planner profiles",
    href: "/event-planners",
    secondaryCta: "Create a provider profile",
    secondaryHref: "/onboarding",
  },
});