/**
 * Web app manifest. ScoutIt had none, so Android offered no install prompt and
 * a home-screen shortcut fell back to a screenshot of the page rather than the
 * mark. `theme_color` matches the `themeColor` already set in layout.js.
 *
 * "maskable" icons carry extra padding because Android launchers crop to their
 * own shape (circle, squircle, teardrop); the "any" icons are used uncropped.
 * Both are generated by scripts/build-icons.mjs from the one vector source.
 */
export default function manifest() {
  return {
    name: "ScoutIt — Property & Space Intelligence Philippines",
    short_name: "ScoutIt",
    description:
      "Property and space intelligence platform for the Philippines. ScoutIt decodes homes, offices, venues, and commercial spaces into clear, structured facts and spatial signals.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#0d0d0d",
    theme_color: "#0e0e0e",
    categories: ["business", "lifestyle", "travel"],
    icons: [
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml" },
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    prefer_related_applications: false,
  };
}
